config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました。'
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました。'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, {:user_ids => []})
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li= message
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      -# .chat-group-form__field--left
      -#   %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      -# .chat-group-form__field--right
      -#   .chat-group-form__search.clearfix
      -#     %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      -#   #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :user_ids, "チャットメンバー", class: 'chat-group-form__label'
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        = f.collection_check_boxes :user_ids, User.all, :id, :name
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        -# #chat-group-users
        -#   #chat-group-user-22.chat-group-user.clearfix
        -#     %input{:name => "chat_group[user_ids][]", :type => "hidden", :value => "22"}/
        -#     %p.chat-group-user__name seo_kyohei
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/groups/index.html.haml
-# left contents area
.left-content
  .user-space
    %p.user-space__user-name 
      %b= current_user.name
    = link_to edit_user_path(current_user) do
      %i.fa.fa-cog
    = link_to new_group_path do
      %i.fa.fa-pencil-square-o
  - current_user.groups.each do |group|
    .group-item
      = link_to group_messages_path(group) do
        %p.group-item__name
          = group.name
        %p.group-item__comment
          メッセージはまだありません。

-# right contents area
.right-content
  .group-space
    %form{:action => "/", :method => "post"}
      %input.group-space__submit{:type => "submit", :value => "edit"}
    %p.group-space__name Sampleグループ
    %p.group-space__member MEMBER: 太郎 次郎 三郎
  .comment-item
    %p.comment-item__name
      %b 太郎
    %p.comment-item__time 18/10/02 06:30:00
    %p.comment-item__comment おはようございます。
  .comment-item
    %p.comment-item__name
      %b 次郎
    %p.comment-item__time 18/10/02 06:20:00
    %p.comment-item__comment こんにちわ。
  .comment-item
    %p.comment-item__name
      %b 三郎
    %p.comment-item__time 18/10/02 06:10:00
    %p.comment-item__comment こんばんわ。
  .post-space
    = form_tag do
      %input.post-space__text{:name => "text", :size => "80", :type => "text", :placeholder => "type a message"}
      %label.upload-label{for: "upload-icon"}
        %i.fa.fa-picture-o
        %input{:type => "file", :id => "upload-icon"}
      %input.post-space__submit{:type => "submit", :value => "Send"}

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li= message
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      -# .chat-group-form__field--left
      -#   %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      -# .chat-group-form__field--right
      -#   .chat-group-form__search.clearfix
      -#     %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      -#   #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :user_ids, "チャットメンバー", class: 'chat-group-form__label'
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        = f.collection_check_boxes :user_ids, User.all, :id, :name
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        -# #chat-group-users
        -#   #chat-group-user-22.chat-group-user.clearfix
        -#     %input{:name => "chat_group[user_ids][]", :type => "hidden", :value => "22"}/
        -#     %p.chat-group-user__name seo_kyohei
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'